# graph_templates.pm -- part of the GWFL RRD-Graph Project
# $Id: graph_templates.pm,v 1.3 2005/11/18 06:55:22 gary Exp $

package graph_templates;

use strict;

require Exporter;
our @ISA = qw(Exporter);
our @EXPORT = qw(%graph_times %graph_templates);
our @EXPORT_OK = qw(%graph_times %graph_templates);

our %graph_times = (
  'Daily' => [ '-1d', 'now', '5 minute average' ],
  'Weekly' => [ '-1w', 'now', '30 minute average' ],
  'Monthly' => [ '-1m', 'now', '2 hour average' ],
  'Yearly' => [ '-1y', 'now', '1 day average' ], 
);

my %iface_graph_templates = (
  'Interface Traffic' => [
    '--vertical-label=Bits per second',
    'DEF:in=RRDFILE:ifinoctets:AVERAGE',
    'CDEF:inbits=in,8,*',
    'AREA:inbits#00CF00:Inbound ',
    'GPRINT:inbits:LAST:Current\: %8.2lf%s',
    'GPRINT:inbits:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:inbits:MAX:Max\: %8.2lf%s\n',
    'DEF:out=RRDFILE:ifoutoctets:AVERAGE',
    'CDEF:outbits=out,8,*',
    'LINE1:outbits#002A97:Outbound',
    'GPRINT:outbits:LAST:Current\: %8.2lf%s',
    'GPRINT:outbits:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:outbits:MAX:Max\: %8.2lf%s',
  ],
  'Interface Errors/Discards' => [
    '--vertical-label=Errors/Discards',
    'DEF:inerr=RRDFILE:ifinerrors:AVERAGE',
    'LINE1:inerr#FF3300:InErrors   ',
    'GPRINT:inerr:LAST:Current\: %8.2lf%s',
    'GPRINT:inerr:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:inerr:MAX:Max\: %8.2lf%s\n',
    'DEF:outerr=RRDFILE:ifouterrors:AVERAGE',
    'LINE1:outerr#CC3300:OutErrors  ',
    'GPRINT:outerr:LAST:Current\: %8.2lf%s',
    'GPRINT:outerr:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:outerr:MAX:Max\: %8.2lf%s\n',
    'DEF:indis=RRDFILE:ifindiscards:AVERAGE',
    'LINE1:indis#FF33CC:InDiscards ',
    'GPRINT:indis:LAST:Current\: %8.2lf%s',
    'GPRINT:indis:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:indis:MAX:Max\: %8.2lf%s\n',
    'DEF:outdis=RRDFILE:ifoutdiscards:AVERAGE',
    'LINE1:outdis#CC33CC:OutDiscards',
    'GPRINT:outdis:LAST:Current\: %8.2lf%s',
    'GPRINT:outdis:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:outdis:MAX:Max\: %8.2lf%s',
  ],
);

my %diskio_graph_templates = (
	'Bytes read/written' => [
    '--vertical-label=Bytes per second',
    '--lower-limit=0',
    '--base=1024',
    'DEF:bread=RRDFILE:bread:AVERAGE',
    'LINE1:bread#00CF00:Bytes read   ',
    'GPRINT:bread:LAST:Current\: %8.2lf%s',
    'GPRINT:bread:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:bread:MAX:Max\: %8.2lf%s\n',
    'DEF:bwritten=RRDFILE:bwritten:AVERAGE',
    'LINE1:bwritten#002A97:Bytes written',
    'GPRINT:bwritten:LAST:Current\: %8.2lf%s',
    'GPRINT:bwritten:AVERAGE:Average\: %8.2lf%s',
    'GPRINT:bwritten:MAX:Max\: %8.2lf%s',
  ],
);	 

my %linux_fs_templates = (
	'FS Bytes Used/Free/Res' => [
		'--vertical-label=Percent Utilised',
    '--lower-limit=0',
		'--upper-limit=100',
		'DEF:res=RRDFILE:reserved:AVERAGE',
		'DEF:util=RRDFILE:usedpercent:AVERAGE',
		'CDEF:free=100.0,util,-',
		'AREA:util#002A97:Space Used:STACK',
		'GPRINT:util:LAST:Current\: %8.2lf%%',
		'GPRINT:util:AVERAGE:Average\: %8.2lf%%',
		'GPRINT:util:MAX:Max\: %8.2lf%%\n',
		'AREA:free#00CF00:Space Free:STACK',
		'GPRINT:free:LAST:Current\: %8.2lf%%',
		'GPRINT:free:AVERAGE:Average\: %8.2lf%%',
		'GPRINT:free:MAX:Max\: %8.2lf%%\n',
		'LINE1:res#FF0000:Reserved  ',
		'GPRINT:res:LAST:Current\: %8.2lf%%',
		'GPRINT:res:AVERAGE:Average\: %8.2lf%%',
		'GPRINT:res:MAX:Max\: %8.2lf%%',
	],
);

our %graph_templates = (

	# Template common to all graphs
  'Template' => [
    '-h 120',
    '-w 500',
    '--rigid',
    '--alt-autoscale-max',
    '--slope-mode',
    'COMMENT: Generated on DATE\c',
    'COMMENT: \n',
  ],

	# Netscreen templates
	'Netscreen' => {
		'CPU Utilisation' => [
  	  '--title=CPU Utilisation - HOST',
  	  '--vertical-label=Percent Utilised',
  	  '--upper-limit=100',
  	  '--lower-limit=0',
  	  'DEF:minx=RRDFILE:1min:AVERAGE',
  	  'DEF:miny=RRDFILE:5min:AVERAGE',
  	  'DEF:minz=RRDFILE:15min:AVERAGE',
  	  'LINE1:minx#002A97:1 minute  ',
  	  'GPRINT:minx:LAST:Current\: %8.2lf%%',
  	  'GPRINT:minx:AVERAGE:Average\: %8.2lf%%',
  	  'GPRINT:minx:MAX:Max\: %8.2lf%%\n',
  	  'LINE1:miny#00FF00:5 minute  ',
  	  'GPRINT:miny:LAST:Current\: %8.2lf%%',
  	  'GPRINT:miny:AVERAGE:Average\: %8.2lf%%',
  	  'GPRINT:miny:MAX:Max\: %8.2lf%%\n',
  	  'LINE1:minz#330000:15 minute ',
  	  'GPRINT:minz:LAST:Current\: %8.2lf%%',
  	  'GPRINT:minz:AVERAGE:Average\: %8.2lf%%',
  	  'GPRINT:minz:MAX:Max\: %8.2lf%%',
  	],
		'RAM Utilisation' => [
    	'--title=RAM Utilisation - HOST',
    	'--vertical-label=Percent Utilised',
    	'--lower-limit=0',
    	'--upper-limit=100',
    	'DEF:used=RRDFILE:usedpercent:AVERAGE',
    	'CDEF:free=100.0,used,-',
    	'AREA:used#002A97:Memory Utilisation',
    	'GPRINT:used:LAST:Current\: %8.2lf%%',
    	'GPRINT:used:AVERAGE:Average\: %8.2lf%%',
    	'GPRINT:used:MAX:Max\: %8.2lf%%\n',
    	'AREA:free#00CF00:Memory Available  :STACK',
    	'GPRINT:free:LAST:Current\: %8.2lf%%',
    	'GPRINT:free:AVERAGE:Average\: %8.2lf%%',
    	'GPRINT:free:MAX:Max\: %8.2lf%%',
  	],
  	'Session Utilisation' => [
    	'--title=Session Utilisation - HOST',
    	'--vertical-label=Sessions',
    	'DEF:used=RRDFILE:used:AVERAGE',
    	'DEF:failed=RRDFILE:failed:AVERAGE',
    	'LINE1:used#002A97:Session Utilisation',
    	'GPRINT:used:LAST:Current\: %8.2lf%s',
    	'GPRINT:used:AVERAGE:Average\: %8.2lf%s',
    	'GPRINT:used:MAX:Max\: %8.2lf%s\n',
    	'LINE1:failed#FF0000:Session Failures   ',
   	 	'GPRINT:failed:LAST:Current\: %8.2lf%s',
   	 	'GPRINT:failed:AVERAGE:Average\: %8.2lf%s',
  	  'GPRINT:failed:MAX:Max\: %8.2lf%s',
  	],
	},

	# Linux templates
	'Linux' => {
	  'Total Processes' => [
	    '--title=Total processes - HOST',
	    '--vertical-label=Total Processes',
	    '--lower-limit=0',
	    'DEF:procs=RRDFILE:numprocesses:AVERAGE',
	    'LINE1:procs#002A97:Total Processes ',
	    'GPRINT:procs:LAST:Current\: %5.0lf%s',
	    'GPRINT:procs:AVERAGE:Average\: %5.0lf%s',
	    'GPRINT:procs:MAX:Max\: %5.0lf%s',
	  ],
	  'RAM Utilisation' => [
	    '--title=RAM Utilisation - HOST',
	    '--vertical-label=Percent Utilised',
	    '--lower-limit=0',
	    '--upper-limit=100',
	    'DEF:used=RRDFILE:usedpercent:AVERAGE',
	    'CDEF:avail=100.0,used,-',
	    'AREA:used#002A97:Memory Utilisation',
	    'GPRINT:used:LAST:Current\: %8.2lf%%',
	    'GPRINT:used:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:used:MAX:Max\: %8.2lf%%\n',
	    'AREA:avail#00CF00:Memory Available  :STACK',
	    'GPRINT:avail:LAST:Current\: %8.2lf%%',	
	    'GPRINT:avail:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:avail:MAX:Max\: %8.2lf%%', 
	  ],
	  'CPU Utilisation' => [
	    '--title=CPU Utilisation - HOST',
	    '--vertical-label=Percent Utilised',
	    '--lower-limit=0',
	    '--upper-limit=100',
	    'DEF:util=RRDFILE:utilpercent:AVERAGE',
	    'CDEF:free=100.0,util,-',
	    'AREA:util#002A97:CPU Utilisation',
	    'GPRINT:util:LAST:Current\: %8.2lf%%',
	    'GPRINT:util:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:util:MAX:Max\: %8.2lf%%\n',
	    'AREA:free#00CF00:CPU Available  :STACK',
	    'GPRINT:free:LAST:Current\: %8.2lf%%',
	    'GPRINT:free:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:free:MAX:Max\: %8.2lf%%',
	  ],
	  'Swap Utilisation' => [
	    '--title=Swap Utilisation - HOST',
	    '--vertical-label=Percent Utilised',
	    '--lower-limit=0',
	    '--upper-limit=100',
	    'DEF:used=RRDFILE:usedpercent:AVERAGE',
	    'CDEF:avail=100.0,used,-',
	    'AREA:used#002A97:Swap Utilisation',
	    'GPRINT:used:LAST:Current\: %8.2lf%%',
	    'GPRINT:used:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:used:MAX:Max\: %8.2lf%%\n',
	    'AREA:avail#00CF00:Swap Available  :STACK',
	    'GPRINT:avail:LAST:Current\: %8.2lf%%',
	    'GPRINT:avail:AVERAGE:Average\: %8.2lf%%',
	    'GPRINT:avail:MAX:Max\: %8.2lf%%',
	  ],
	  'Load Average' => [
	    '--title=Load Average - HOST',
	    '--vertical-label=Load Average',
	    '--lower-limit=0',
	    '--units-exponent=0',
			'DEF:minx=RRDFILE:1min:AVERAGE',
	    'DEF:miny=RRDFILE:5min:AVERAGE',
	    'DEF:minz=RRDFILE:15min:AVERAGE',
	    'LINE1:minx#002A97:1 minute  ',
	    'GPRINT:minx:LAST:Current\: %8.2lf',
	    'GPRINT:minx:AVERAGE:Average\: %8.2lf',
	    'GPRINT:minx:MAX:Max\: %8.2lf\n',
	    'LINE1:miny#00FF00:5 minute  ',
	    'GPRINT:miny:LAST:Current\: %8.2lf',
	    'GPRINT:miny:AVERAGE:Average\: %8.2lf',
	    'GPRINT:miny:MAX:Max\: %8.2lf\n',
	    'LINE1:minz#330000:15 minute ',
	    'GPRINT:minz:LAST:Current\: %8.2lf',
	    'GPRINT:minz:AVERAGE:Average\: %8.2lf',
	    'GPRINT:minz:MAX:Max\: %8.2lf',
	  ],
	  'DL360G4 Temperatures' => [
	    '--title=Temperatures - HOST',
	    '--vertical-label=Degrees Celsius',
	    '--lower-limit=0',
	    '--upper-limit=100',
	    'DEF:IOzone=RRDFILE:IOzone:AVERAGE',
	    'LINE1:IOzone#002A97:IO Zone   ',
	    'GPRINT:IOzone:LAST:Current\: %3.1lf C',
	    'GPRINT:IOzone:AVERAGE:Average\: %3.1lf C',
	    'GPRINT:IOzone:MAX:Max\: %3.1lf C\n',
	    'DEF:CPU1=RRDFILE:CPU1:AVERAGE',
	    'LINE1:CPU1#00FF00:CPU 1     ',
	    'GPRINT:CPU1:LAST:Current\: %3.1lf C',
	    'GPRINT:CPU1:AVERAGE:Average\: %3.1lf C',
	    'GPRINT:CPU1:MAX:Max\: %3.1lf C\n',
	    'DEF:CPU2=RRDFILE:CPU2:AVERAGE',
	    'LINE1:CPU2#330000:CPU 2     ',
	    'GPRINT:CPU2:LAST:Current\: %3.1lf C',
	    'GPRINT:CPU2:AVERAGE:Average\: %3.1lf C',
	    'GPRINT:CPU2:MAX:Max\: %3.1lf C\n',
	    'DEF:PSU=RRDFILE:PSUbay:AVERAGE',
	    'LINE1:PSU#FFFF00:PSU Bay   ',
	    'GPRINT:PSU:LAST:Current\: %3.1lf C',
	    'GPRINT:PSU:AVERAGE:Average\: %3.1lf C',
	    'GPRINT:PSU:MAX:Max\: %3.1lf C\n',
	    'DEF:SYS=RRDFILE:SYSboard:AVERAGE',
	    'LINE1:SYS#FF0000:Sys Board ',
	    'GPRINT:SYS:LAST:Current\: %3.1lf C',
	    'GPRINT:SYS:AVERAGE:Average\: %3.1lf C',
	    'GPRINT:SYS:MAX:Max\: %3.1lf C',
	  ],
		'DL360G3 Temperatures' => [
      '--title=Temperatures - HOST',
      '--vertical-label=Degrees Celsius',
      '--lower-limit=0',
      '--upper-limit=100',
      'DEF:CPUzone=RRDFILE:CPUzone:AVERAGE',
      'LINE1:CPUzone#002A97:CPU Zone  ',
      'GPRINT:CPUzone:LAST:Current\: %3.1lf C',
      'GPRINT:CPUzone:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPUzone:MAX:Max\: %3.1lf C\n',
      'DEF:CPU1=RRDFILE:CPU1:AVERAGE',
      'LINE1:CPU1#00FF00:CPU 1     ',
      'GPRINT:CPU1:LAST:Current\: %3.1lf C',
      'GPRINT:CPU1:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPU1:MAX:Max\: %3.1lf C\n',
      'DEF:IOzone=RRDFILE:IOzone:AVERAGE',
      'LINE1:IOzone#FF0000:IO Zone   ',
      'GPRINT:IOzone:LAST:Current\: %3.1lf C',
      'GPRINT:IOzone:AVERAGE:Average\: %3.1lf C',
      'GPRINT:IOzone:MAX:Max\: %3.1lf C\n',
			'DEF:CPU2=RRDFILE:CPU2:AVERAGE',
      'LINE1:CPU2#330000:CPU 2     ',
      'GPRINT:CPU2:LAST:Current\: %3.1lf C',
      'GPRINT:CPU2:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPU2:MAX:Max\: %3.1lf C',
    ],
		'DL380G4 Temperatures' => [
      '--title=Temperatures - HOST',
      '--vertical-label=Degrees Celsius',
      '--lower-limit=0',
      '--upper-limit=100',
      'DEF:CPUzone=RRDFILE:CPUzone:AVERAGE',
      'LINE1:CPUzone#002A97:CPU Zone  ',
      'GPRINT:CPUzone:LAST:Current\: %3.1lf C',
      'GPRINT:CPUzone:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPUzone:MAX:Max\: %3.1lf C\n',
      'DEF:CPU1=RRDFILE:CPU1:AVERAGE',
      'LINE1:CPU1#00FF00:CPU 1     ',
      'GPRINT:CPU1:LAST:Current\: %3.1lf C',
      'GPRINT:CPU1:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPU1:MAX:Max\: %3.1lf C\n',
      'DEF:IOzone=RRDFILE:IOzone:AVERAGE',
      'LINE1:IOzone#FF0000:IO Zone   ',
      'GPRINT:IOzone:LAST:Current\: %3.1lf C',
      'GPRINT:IOzone:AVERAGE:Average\: %3.1lf C',
      'GPRINT:IOzone:MAX:Max\: %3.1lf C\n',
      'DEF:CPU2=RRDFILE:CPU2:AVERAGE',
      'LINE1:CPU2#330000:CPU 2     ',
      'GPRINT:CPU2:LAST:Current\: %3.1lf C',
      'GPRINT:CPU2:AVERAGE:Average\: %3.1lf C',
      'GPRINT:CPU2:MAX:Max\: %3.1lf C\n',
			'DEF:PSU=RRDFILE:PSUbay:AVERAGE',
      'LINE1:PSU#FFFF00:PSU Bay   ',
      'GPRINT:PSU:LAST:Current\: %3.1lf C',
      'GPRINT:PSU:AVERAGE:Average\: %3.1lf C',
      'GPRINT:PSU:MAX:Max\: %3.1lf C',
    ],
	  'FS: /' => [
	    '--title=Filesystem (/)- HOST',
			@{$linux_fs_templates{'FS Bytes Used/Free/Res'}},
	  ],
	  'FS: /var' => [
	    '--title=Filesystem (/var)- HOST',
			@{$linux_fs_templates{'FS Bytes Used/Free/Res'}},
	  ],
		'Disk IO - /dev/cciss/c0d0' => [ 
			'--title=Disk IO  - /dev/cciss/c0d0 - HOST',
			@{$diskio_graph_templates{'Bytes read/written'}}, 
		],
	},

	# ICMP templates
	'ICMP' => {
	  'PING Latency' => [
	    '--title=PING Latency - HOST',
	    '--vertical-label=milliseconds',
	    '--lower-limit=0',
	    'DEF:rtt=RRDFILE:rta:AVERAGE',
	    'DEF:pl=RRDFILE:packetloss:AVERAGE',
	    'CDEF:zero=pl,0,0,LIMIT,UN,UNKN,INF,IF',
	    'CDEF:ten=pl,1,10,LIMIT,UN,UNKN,INF,IF',
	    'CDEF:twe=pl,11,25,LIMIT,UN,UNKN,INF,IF',
	    'CDEF:fif=pl,26,50,LIMIT,UN,UNKN,INF,IF',
	    'CDEF:sev=pl,51,75,LIMIT,UN,UNKN,INF,IF',
	    'CDEF:hun=pl,76,100,LIMIT,UN,UNKN,INF,IF',	
	    'AREA:rtt#002A97:Ping RTT',
	    'GPRINT:rtt:LAST: Current\: %8.2lf ms',
	    'GPRINT:rtt:AVERAGE: Average\: %8.2lf ms',
	    'GPRINT:rtt:MAX: Max\:%8.2lf ms\n',
	    'COMMENT:\n',
	    'COMMENT:Packet Loss (',
	    'AREA:zero#00CF00: 0 %:STACK',
	    'AREA:ten#6C9BCD: 1-10 %:STACK',
	    'AREA:twe#FFFF00: 11-25 %:STACK',
	    'AREA:fif#FFCC66: 26-50 %:STACK',
	    'AREA:sev#FF9900: 51-75 %:STACK',
	    'AREA:hun#FF0000: 76-100 %  ):STACK',
	  ],
	},

	# Cisco Switch templates
	'Cisco Switch' => {
		'CPU Utilisation' => [
      '--title=CPU Utilisation - HOST',
      '--vertical-label=Percent Utilised',
      '--upper-limit=100',
      '--lower-limit=0',
      'DEF:minx=RRDFILE:1min:AVERAGE',
      'DEF:miny=RRDFILE:5min:AVERAGE',
      'LINE1:minx#002A97:1 minute  ',
      'GPRINT:minx:LAST:Current\: %8.2lf%%',
      'GPRINT:minx:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:minx:MAX:Max\: %8.2lf%%\n',
      'LINE1:miny#00FF00:5 minute  ',
      'GPRINT:miny:LAST:Current\: %8.2lf%%',
      'GPRINT:miny:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:miny:MAX:Max\: %8.2lf%%',
    ],
		'Memory Utilisation' => [
			'--title=Physical memory - HOST',
      '--vertical-label=Percent Utilised',
      '--lower-limit=0',
      '--upper-limit=100',
      'DEF:used=RRDFILE:used:AVERAGE',
      'CDEF:free=100.0,used,-',
      'AREA:used#002A97:Memory Utilisation',
      'GPRINT:used:LAST:Current\: %8.2lf%%',
      'GPRINT:used:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:used:MAX:Max\: %8.2lf%%\n',
      'AREA:free#00CF00:Memory Available  :STACK',
      'GPRINT:free:LAST:Current\: %8.2lf%%',
      'GPRINT:free:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:free:MAX:Max\: %8.2lf%%',
    ],
		'Interface 1/1 Traffic' => [
			'--title=Traffic for Interface GE 1/1',
			@{$iface_graph_templates{'Interface Traffic'}},
		],
		'Interface 1/1 Errors/Discards' => [
			'--title=Errors/Discards for Interface GE 1/1',
			@{$iface_graph_templates{'Interface Errors/Discards'}},
		],
	},
	
	# Cisco CSS templates
	'Cisco CSS' => {
		'CPU Utilisation' => [
      '--title=CPU Utilisation - HOST',
      '--vertical-label=Percent Utilised',
      '--upper-limit=100',
      '--lower-limit=0',
      'DEF:minx=RRDFILE:current:AVERAGE',
      'DEF:miny=RRDFILE:average:AVERAGE',
      'LINE1:minx#002A97:Current',
      'GPRINT:minx:LAST:Current\: %8.2lf%%',
      'GPRINT:minx:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:minx:MAX:Max\: %8.2lf%%\n',
      'LINE1:miny#00FF00:Average',
      'GPRINT:miny:LAST:Current\: %8.2lf%%',
      'GPRINT:miny:AVERAGE:Average\: %8.2lf%%',
      'GPRINT:miny:MAX:Max\: %8.2lf%%',
    ],
	},		
);              

1;
